// =============================================================================
//  Generate supabase/seed_players.sql — every FIFA fantasy player + best-effort
//  real-life `club` (the FIFA feed has no club field, so the United-Clubs rule
//  needs this). Run: `node scripts/gen-clubs.mjs`
//
//  CLUBS is keyed by `COUNTRY|displayName` where displayName = knownName ||
//  `${firstName} ${lastName}`. Unknown players get NULL club (rule skipped for
//  them). Values reflect best-effort knowledge as of early 2026 and may be stale
//  — re-run this script with an updated map to refresh.
// =============================================================================
import { writeFileSync } from 'fs'

const PLAYERS_URL = 'https://play.fifa.com/json/fantasy/players.json'
const SQUADS_URL  = 'https://play.fifa.com/json/fantasy/squads.json'

const CLUBS = {
  // ── Forwards / wingers / attacking mids (high price) ──
  'ENG|Harry Kane': 'Bayern Munich',
  'FRA|Kylian Mbappé': 'Real Madrid',
  'NOR|Erling Haaland': 'Manchester City',
  'ARG|Lionel Messi': 'Inter Miami',
  'BRA|Vinícius Júnior': 'Real Madrid',
  'FRA|Ousmane Dembélé': 'Paris Saint-Germain',
  'ESP|Lamine Yamal': 'Barcelona',
  'POR|Cristiano Ronaldo': 'Al Nassr',
  'EGY|Mohamed Salah': 'Liverpool',
  'ENG|Bukayo Saka': 'Arsenal',
  'FRA|Michael Olise': 'Bayern Munich',
  'ARG|Lautaro Martínez': 'Inter',
  'ARG|Julián Alvarez': 'Atlético Madrid',
  'POR|Bruno Fernandes': 'Manchester United',
  'ENG|Jude Bellingham': 'Real Madrid',
  'BRA|Raphinha': 'Barcelona',
  'COL|Luis Díaz': 'Bayern Munich',
  'ESP|Mikel Oyarzabal': 'Real Sociedad',
  'ESP|Pedri': 'Barcelona',
  'FRA|Rayan Cherki': 'Manchester City',
  'FRA|Bradley Barcola': 'Paris Saint-Germain',
  'SWE|Alexander Isak': 'Liverpool',
  'GER|Jamal Musiala': 'Bayern Munich',
  'ENG|Eberechi Eze': 'Arsenal',
  'ENG|Ollie Watkins': 'Aston Villa',
  'EGY|Omar Marmoush': 'Manchester City',
  'GER|Kai Havertz': 'Arsenal',
  'ESP|Ferran Torres': 'Barcelona',
  'SWE|Viktor Gyökeres': 'Arsenal',
  'POR|Bernardo Silva': 'Manchester City',
  'POR|Rafael Leão': 'Milan',
  'ESP|Nico Williams': 'Athletic Club',
  'NED|Cody Gakpo': 'Liverpool',
  'ESP|Dani Olmo': 'Barcelona',
  'NOR|Martin Ødegaard': 'Arsenal',
  'SEN|Sadio Mané': 'Al Nassr',
  'ARG|Enzo Fernández': 'Chelsea',
  'BEL|Jérémy Doku': 'Manchester City',
  'BEL|Kevin De Bruyne': 'Napoli',
  'ENG|Marcus Rashford': 'Barcelona',
  'FRA|Marcus Thuram': 'Inter',
  'FRA|Désiré Doué': 'Paris Saint-Germain',
  'GER|Florian Wirtz': 'Liverpool',
  'POR|Gonçalo Ramos': 'Paris Saint-Germain',
  'ESP|Rodri': 'Manchester City',
  'SUI|Breel Embolo': 'Monaco',
  'URU|Darwin Núñez': 'Al Hilal',
  'URU|Federico Valverde': 'Real Madrid',
  'ENG|Ivan Toney': 'Al Ahli',
  'BEL|Romelu Lukaku': 'Napoli',
  'GER|Leroy Sané': 'Galatasaray',
  'KOR|Son Heung-Min': 'Los Angeles FC',
  'NED|Memphis Depay': 'Corinthians',
  'BRA|Matheus Cunha': 'Manchester United',
  'CZE|Patrik Schick': 'Bayer Leverkusen',
  'ENG|Morgan Rogers': 'Aston Villa',
  'GER|Nick Woltemade': 'Newcastle United',
  'BRA|Neymar': 'Santos',
  'KSA|Salem Al Dawsari': 'Al Hilal',
  'GHA|Antoine Semenyo': 'Bournemouth',
  'TUR|Hakan Çalhanoglu': 'Inter',
  'CAN|Jonathan David': 'Juventus',
  'ENG|Anthony Gordon': 'Newcastle United',
  'ENG|Declan Rice': 'Arsenal',
  'JPN|Ayase Ueda': 'Feyenoord',
  'MEX|Raúl Jiménez': 'Fulham',
  'TUR|Kenan Yildiz': 'Juventus',
  'TUR|Arda Güler': 'Real Madrid',
  'USA|Christian Pulisic': 'Milan',
  'JPN|Takefusa Kubo': 'Real Sociedad',
  'NED|Frenkie de Jong': 'Barcelona',
  'AUT|Marcel Sabitzer': 'Borussia Dortmund',
  'CRO|Ante Budimir': 'Osasuna',
  'ECU|Moisés Caicedo': 'Chelsea',
  'MAR|Ismael Saibari': 'PSV',
  'NED|Quinten Timber': 'Feyenoord',
  'NOR|Alexander Sørloth': 'Atlético Madrid',
  'PAR|Diego Gómez': 'Brighton & Hove Albion',
  'ESP|Borja Iglesias': 'Celta Vigo',
  'SUI|Dan Ndoye': 'Nottingham Forest',
  'SUI|Rubén Vargas': 'Sevilla',
  'BRA|Bruno Guimarães': 'Newcastle United',
  'MEX|Santiago Giménez': 'Milan',
  'ESP|Fabián Ruiz': 'Paris Saint-Germain',
  'AUT|Christoph Baumgartner': 'RB Leipzig',
  'SEN|Nicolas Jackson': 'Bayern Munich',
  'ARG|Alexis Mac Allister': 'Liverpool',
  'GER|Deniz Undav': 'VfB Stuttgart',
  'PAR|Julio Enciso': 'Brighton & Hove Albion',
  'BEL|Leandro Trossard': 'Arsenal',
  'ALG|Riyad Mahrez': 'Al Ahli',
  'ARG|Thiago Almada': 'Atlético Madrid',
  'BRA|Gabriel Martinelli': 'Arsenal',
  'BRA|Lucas Paquetá': 'West Ham United',
  'COL|James Rodríguez': 'Club León',
  'COD|Cédric Bakambu': 'Real Betis',
  'CRO|Martin Baturina': 'Como',
  'ENG|Elliot Anderson': 'Nottingham Forest',
  'FRA|Aurélien Tchouaméni': 'Real Madrid',
  'NED|Xavi Simons': 'Tottenham Hotspur',
  'NED|Tijjani Reijnders': 'Manchester City',
  'PAN|Adalberto Carrasquilla': 'Pumas UNAM',
  'POR|João Félix': 'Al Nassr',
  'POR|João Neves': 'Paris Saint-Germain',
  'SCO|Scott McTominay': 'Napoli',
  'SEN|Iliman Ndiaye': 'Everton',
  'URU|Giorgian de Arrascaeta': 'Flamengo',
  'ARG|Emiliano Buendía': 'Aston Villa',
  'CZE|Adam Hlozek': 'Hoffenheim',
  'FRA|Jean-Philippe Mateta': 'Crystal Palace',
  'NZL|Chris Wood': 'Nottingham Forest',
  'GER|Maximilian Beier': 'Borussia Dortmund',
  'NOR|Fredrik Aursnes': 'Benfica',
  'ESP|Gavi': 'Barcelona',
  'NED|Justin Kluivert': 'Bournemouth',
  'CRO|Mario Pasalic': 'Atalanta',
  'FRA|Adrien Rabiot': 'Milan',
  'FRA|Maghnes Akliouche': 'Monaco',
  'MEX|Álvaro Fidalgo': 'Club América',
  'POR|Pedro Neto': 'Chelsea',
  'POR|Vitinha': 'Paris Saint-Germain',
  'GER|Jamie Leweling': 'VfB Stuttgart',
  'GHA|Abdul Fatawu': 'Leicester City',
  'MAR|Brahim Díaz': 'Real Madrid',
  'BRA|Casemiro': 'Manchester United',
  'COL|Jhon Arias': 'Wolverhampton Wanderers',
  'COL|Cucho Hernández': 'Real Betis',
  'MEX|César Huerta': 'Anderlecht',
  'GER|Nadiem Amiri': 'Mainz 05',
  'BRA|Éderson': 'Atalanta',
  'ALG|Mohammed Amoura': 'VfL Wolfsburg',
  'ALG|Amine Gouiri': 'Marseille',
  'ALG|Farès Chaïbi': 'Eintracht Frankfurt',
  'ARG|Valentín Barco': 'Strasbourg',
  'BIH|Ermedin Demirovic': 'VfB Stuttgart',
  'CAN|Cyle Larin': 'Mallorca',
  'COD|Yoane Wissa': 'Newcastle United',
  'CRO|Andrej Kramaric': 'Hoffenheim',
  'CRO|Luka Modric': 'Milan',
  'KOR|Lee Jae-Sung': 'Mainz 05',
  'MEX|Orbelín Pineda': 'AEK Athens',
  'NED|Teun Koopmeiners': 'Juventus',
  'NOR|Andreas Schjelderup': 'Benfica',
  'NOR|Kristian Thorstvedt': 'Sassuolo',
  'SEN|Ismaïla Sarr': 'Crystal Palace',
  'SEN|Lamine Camara': 'Monaco',
  'SEN|Habib Diarra': 'Sunderland',
  'SUI|Granit Xhaka': 'Sunderland',
  'SUI|Fabian Rieder': 'Rennes',
  'TUR|Kerem Aktürkoglu': 'Fenerbahçe',
  'URU|Brian Rodríguez': 'Club América',
  'USA|Johnny Cardoso': 'Atlético Madrid',
  'UZB|Abbosbek Fayzullaev': 'CSKA Moscow',
  'ARG|Giovani Lo Celso': 'Real Betis',
  'ARG|Matías Soulé': 'Roma',
  'GHA|Thomas Partey': 'Villarreal',
  'ESP|Mikel Merino': 'Arsenal',
  'MAR|Bilal El Khannouss': 'VfB Stuttgart',
  'BEL|Youri Tielemans': 'Aston Villa',
  'BIH|Edin Dzeko': 'Fiorentina',
  'COL|Jhon Córdoba': 'Krasnodar',
  'COL|Jorge Carrascal': 'Flamengo',
  'CRO|Nikola Vlasic': 'Torino',
  'ENG|Noni Madueke': 'Arsenal',
  'ENG|Kobbie Mainoo': 'Manchester United',
  'FRA|Warren Zaïre-Emery': 'Paris Saint-Germain',
  'FRA|Manu Koné': 'Roma',
  'GER|Leon Goretzka': 'Bayern Munich',
  'KOR|Hwang Hee-Chan': 'Wolverhampton Wanderers',
  'KOR|Lee Kang-In': 'Paris Saint-Germain',
  'NED|Donyell Malen': 'Aston Villa',
  'NED|Ryan Gravenberch': 'Liverpool',
  'NED|Jerdy Schouten': 'PSV',
  'NOR|Antonio Nusa': 'RB Leipzig',
  'POR|Matheus Nunes': 'Manchester City',
  'SEN|Krépin Diatta': 'Monaco',
  'ESP|Martín Zubimendi': 'Arsenal',
  'SWE|Mattias Svanberg': 'VfL Wolfsburg',
  'SUI|Djibril Sow': 'Sevilla',
  'SUI|Denis Zakaria': 'Monaco',
  'TUR|Baris Alper Yilmaz': 'Galatasaray',
  'USA|Malik Tillman': 'Bayer Leverkusen',
  'USA|Weston McKennie': 'Juventus',
  'ARG|Exequiel Palacios': 'Bayer Leverkusen',
  'AUT|Marko Arnautovic': 'Red Star Belgrade',
  'AUT|Michael Gregoritsch': 'Freiburg',
  'AUT|Romano Schmid': 'Werder Bremen',
  'AUT|Patrick Wimmer': 'VfL Wolfsburg',
  'PAR|Miguel Almirón': 'Atlanta United',
  'SCO|John McGinn': 'Aston Villa',
  'ESP|Álex Baena': 'Atlético Madrid',
  'TUR|Orkun Kökçü': 'Benfica',
  'USA|Folarin Balogun': 'Monaco',
  'ARG|Santiago Castro': 'Bologna',
  'JPN|Wataru Endo': 'Liverpool',
  'MEX|Edson Álvarez': 'Fenerbahçe',
  'CRO|Mateo Kovacic': 'Manchester City',
  'ECU|Nilson Angulo': 'Anderlecht',
  'MAR|Achraf Hakimi': 'Paris Saint-Germain',
  'AUS|Cristian Volpato': 'Sassuolo',
  'URU|Rodrigo Bentancur': 'Tottenham Hotspur',
  'ARG|Rodrigo De Paul': 'Inter Miami',
  'ARG|Nico Paz': 'Como',
  'AUS|Riley McGree': 'Middlesbrough',
  'BEL|Amadou Onana': 'Aston Villa',
  'BRA|Igor Thiago': 'Brentford',
  'CIV|Nicolas Pépé': 'Villarreal',
  'CIV|Amad Diallo': 'Manchester United',
  'CIV|Franck Kessie': 'Al Ahli',
  'CZE|Lukás Provod': 'Slavia Prague',
  'KOR|Bae Jun-Ho': 'Stoke City',
  'MEX|Carlos Rodríguez': 'Cruz Azul',
  'MAR|Ayoub El Kaabi': 'Olympiacos',
  'NED|Noa Lang': 'Napoli',
  'POR|Trincão': 'Sporting CP',
  'POR|Rúben Neves': 'Al Hilal',
  'QAT|Akram Afif': 'Al Sadd',
  'SEN|Pape Gueye': 'Villarreal',
  'ESP|Yéremy Pino': 'Crystal Palace',
  'SUI|Remo Freuler': 'Bologna',
  'URU|Manuel Ugarte': 'Manchester United',
  'USA|Ricardo Pepi': 'PSV',
  'MEX|Diego Lainez': 'Tigres UANL',
  'RSA|Patrick Maswanganyi': 'Orlando Pirates',
  'GHA|Iñaki Williams': 'Athletic Club',

  // ── Star goalkeepers ──
  'ARG|Emiliano Martínez': 'Aston Villa',
  'BRA|Alisson': 'Liverpool',
  'ESP|Unai Simón': 'Athletic Club',
  'FRA|Mike Maignan': 'Milan',
  'ENG|Jordan Pickford': 'Everton',
  'POR|Diogo Costa': 'Porto',
  'GER|Marc-André ter Stegen': 'Barcelona',
  'BEL|Thibaut Courtois': 'Real Madrid',
  'NED|Bart Verbruggen': 'Brighton & Hove Albion',
  'MAR|Yassine Bounou': 'Al Hilal',
  'USA|Matt Turner': 'New England Revolution',

  // ── Star defenders ──
  'NED|Virgil van Dijk': 'Liverpool',
  'ENG|John Stones': 'Manchester City',
  'POR|Rúben Dias': 'Manchester City',
  'ESP|Dani Carvajal': 'Real Madrid',
  'FRA|William Saliba': 'Arsenal',
  'GER|Antonio Rüdiger': 'Real Madrid',
  'CRO|Joško Gvardiol': 'Manchester City',
  'NED|Nathan Aké': 'Manchester City',
  'ARG|Cristian Romero': 'Tottenham Hotspur',
  'URU|Ronald Araújo': 'Barcelona',
  'ENG|Trent Alexander-Arnold': 'Real Madrid',
  'FRA|Theo Hernández': 'Al Hilal',
  'ESP|Pau Cubarsí': 'Barcelona',
  'GER|Joshua Kimmich': 'Bayern Munich',
  'NED|Denzel Dumfries': 'Inter',
  'ENG|Kyle Walker': 'Burnley',
  'POR|Nuno Mendes': 'Paris Saint-Germain',
  'BRA|Marquinhos': 'Paris Saint-Germain',
  'KOR|Kim Min-Jae': 'Bayern Munich',
  'MAR|Noussair Mazraoui': 'Manchester United',
  'CAN|Alphonso Davies': 'Bayern Munich',
}

function displayName(p) {
  if (p.knownName) return p.knownName
  return [p.firstName, p.lastName].filter(Boolean).join(' ').trim() || `Player ${p.id}`
}
const esc = s => String(s).replace(/'/g, "''")

const [players, squads] = await Promise.all([
  fetch(PLAYERS_URL).then(r => r.json()),
  fetch(SQUADS_URL).then(r => r.json()),
])
const abbr = {}; squads.forEach(s => { abbr[s.id] = s.abbr })

let matched = 0
const rows = players.map(p => {
  const country = abbr[p.squadId] || ''
  const name = displayName(p)
  const club = CLUBS[`${country}|${name}`] || null
  if (club) matched++
  const clubSql = club ? `'${esc(club)}'` : 'null'
  return `  (${p.id}, '${esc(name)}', '${esc(country)}', '${esc(p.position)}', ${clubSql})`
})

const sql = `-- =============================================================================
--  Fantasy World Cup 2026 — players seed (${players.length} players, ${matched} with club)
--  Generated by scripts/gen-clubs.mjs. Run AFTER schema.sql.
--  Supplies the real-life \`club\` used by the United-Clubs rule; live price/points
--  still come from the FIFA API at runtime. Re-running replaces all rows.
-- =============================================================================
delete from public.players;

insert into public.players (id, name, country, position, club) values
${rows.join(',\n')};
`

writeFileSync('supabase/seed_players.sql', sql)
console.log(`wrote supabase/seed_players.sql — ${players.length} players, ${matched} with a club`)
