// =============================================================================
//  FIFA World Cup 2026 - Tournament Data
// =============================================================================

export const TIMEZONES = [
  { id: 'hst',   label: 'Honolulu',                offset: -10,  abbr: 'HST',  iana: ['Pacific/Honolulu', 'Pacific/Pago_Pago'] },
  { id: 'akdt',  label: 'Anchorage',               offset:  -9,  abbr: 'AKDT', iana: ['America/Anchorage', 'America/Juneau', 'America/Nome'] },
  { id: 'pdt',   label: 'Los Angeles / Vancouver',  offset:  -7,  abbr: 'PDT',  iana: ['America/Los_Angeles', 'America/Vancouver', 'America/Tijuana', 'America/Phoenix'] },
  { id: 'mdt',   label: 'Denver',                  offset:  -6,  abbr: 'MDT',  iana: ['America/Denver', 'America/Boise', 'America/Edmonton'] },
  { id: 'cdt',   label: 'Chicago / Mexico City',   offset:  -5,  abbr: 'CDT',  iana: ['America/Chicago', 'America/Mexico_City', 'America/Winnipeg', 'America/Guatemala'] },
  { id: 'edt',   label: 'New York / Toronto',      offset:  -4,  abbr: 'EDT',  iana: ['America/New_York', 'America/Toronto', 'America/Detroit', 'America/Indiana/Indianapolis', 'America/Halifax'] },
  { id: 'brt',   label: 'São Paulo',               offset:  -3,  abbr: 'BRT',  iana: ['America/Sao_Paulo', 'America/Fortaleza', 'America/Recife', 'America/Manaus'] },
  { id: 'art',   label: 'Buenos Aires',            offset:  -3,  abbr: 'ART',  iana: ['America/Argentina/Buenos_Aires', 'America/Argentina/Cordoba', 'America/Montevideo', 'America/Asuncion'] },
  { id: 'utc',   label: 'UTC',                     offset:   0,  abbr: 'UTC',  iana: ['UTC', 'Etc/UTC', 'Etc/GMT'] },
  { id: 'bst',   label: 'London',                  offset:  +1,  abbr: 'BST',  iana: ['Europe/London', 'Europe/Dublin'] },
  { id: 'west',  label: 'Lisbon',                  offset:  +1,  abbr: 'WEST', iana: ['Europe/Lisbon', 'Atlantic/Canary'] },
  { id: 'cest',  label: 'Paris / Berlin / Madrid', offset:  +2,  abbr: 'CEST', iana: ['Europe/Paris', 'Europe/Berlin', 'Europe/Madrid', 'Europe/Rome', 'Europe/Amsterdam', 'Europe/Brussels', 'Europe/Vienna', 'Europe/Warsaw', 'Europe/Prague', 'Europe/Stockholm', 'Europe/Zurich', 'Europe/Oslo', 'Europe/Copenhagen', 'Europe/Budapest', 'Europe/Belgrade', 'Europe/Sarajevo', 'Europe/Zagreb'] },
  { id: 'eest',  label: 'Helsinki / Athens',       offset:  +3,  abbr: 'EEST', iana: ['Europe/Helsinki', 'Europe/Athens', 'Europe/Bucharest', 'Europe/Sofia', 'Europe/Kyiv', 'Europe/Kiev', 'Europe/Vilnius', 'Europe/Riga', 'Europe/Tallinn', 'Asia/Jerusalem', 'Asia/Beirut', 'Asia/Nicosia'] },
  { id: 'msk',   label: 'Moscow',                  offset:  +3,  abbr: 'MSK',  iana: ['Europe/Moscow', 'Europe/Minsk', 'Europe/Kaliningrad'] },
  { id: 'ast',   label: 'Riyadh',                  offset:  +3,  abbr: '+03',  iana: ['Asia/Riyadh', 'Asia/Kuwait', 'Asia/Baghdad', 'Asia/Aden', 'Asia/Qatar'] },
  { id: 'gst',   label: 'Dubai',                   offset:  +4,  abbr: 'GST',  iana: ['Asia/Dubai', 'Asia/Muscat'] },
  { id: 'pkt',   label: 'Karachi',                 offset:  +5,  abbr: 'PKT',  iana: ['Asia/Karachi'] },
  { id: 'ist',   label: 'Kolkata / New Delhi',     offset:  5.5, abbr: 'IST',  iana: ['Asia/Kolkata', 'Asia/Calcutta'] },
  { id: 'bdt',   label: 'Dhaka',                   offset:  +6,  abbr: 'BDT',  iana: ['Asia/Dhaka', 'Asia/Almaty'] },
  { id: 'ict',   label: 'Bangkok',                 offset:  +7,  abbr: 'ICT',  iana: ['Asia/Bangkok', 'Asia/Ho_Chi_Minh', 'Asia/Jakarta', 'Asia/Phnom_Penh'] },
  { id: 'sgt',   label: 'Singapore',               offset:  +8,  abbr: 'SGT',  iana: ['Asia/Singapore', 'Asia/Kuala_Lumpur'] },
  { id: 'cst',   label: 'Beijing / Shanghai',      offset:  +8,  abbr: 'CST',  iana: ['Asia/Shanghai', 'Asia/Hong_Kong', 'Asia/Taipei', 'Asia/Macau', 'Asia/Urumqi'] },
  { id: 'awst',  label: 'Perth',                   offset:  +8,  abbr: 'AWST', iana: ['Australia/Perth'] },
  { id: 'jst',   label: 'Tokyo',                   offset:  +9,  abbr: 'JST',  iana: ['Asia/Tokyo'] },
  { id: 'kst',   label: 'Seoul',                   offset:  +9,  abbr: 'KST',  iana: ['Asia/Seoul', 'Asia/Pyongyang'] },
  { id: 'aest',  label: 'Sydney / Melbourne',      offset: +10,  abbr: 'AEST', iana: ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane', 'Australia/Hobart'] },
  { id: 'nzst',  label: 'Auckland',                offset: +12,  abbr: 'NZST', iana: ['Pacific/Auckland', 'Pacific/Fiji'] },
]

export const TEAMS = {
  MEX: { name: 'Mexico',          flag: '🇲🇽', group: 'A', conf: 'CONCACAF', ranking: 16, wcWins: 0, wcApps: 17, color: '#006847' },
  RSA: { name: 'South Africa',    flag: '🇿🇦', group: 'A', conf: 'CAF',      ranking: 68, wcWins: 0, wcApps:  3, color: '#007A4D' },
  KOR: { name: 'South Korea',     flag: '🇰🇷', group: 'A', conf: 'AFC',      ranking: 23, wcWins: 0, wcApps: 11, color: '#C60C30' },
  CZE: { name: 'Czechia',         flag: '🇨🇿', group: 'A', conf: 'UEFA',     ranking: 46, wcWins: 0, wcApps: 10, color: '#D7141A' },
  CAN: { name: 'Canada',          flag: '🇨🇦', group: 'B', conf: 'CONCACAF', ranking: 30, wcWins: 0, wcApps:  2, color: '#FF0000' },
  BIH: { name: 'Bosnia & Herz.',  flag: '🇧🇦', group: 'B', conf: 'UEFA',     ranking: 54, wcWins: 0, wcApps:  1, color: '#002395' },
  QAT: { name: 'Qatar',           flag: '🇶🇦', group: 'B', conf: 'AFC',      ranking: 95, wcWins: 0, wcApps:  2, color: '#8D1B3D' },
  SUI: { name: 'Switzerland',     flag: '🇨🇭', group: 'B', conf: 'UEFA',     ranking: 23, wcWins: 0, wcApps: 12, color: '#FF0000' },
  BRA: { name: 'Brazil',          flag: '🇧🇷', group: 'C', conf: 'CONMEBOL', ranking:  5, wcWins: 5, wcApps: 22, color: '#009C3B' },
  MAR: { name: 'Morocco',         flag: '🇲🇦', group: 'C', conf: 'CAF',      ranking: 14, wcWins: 0, wcApps:  7, color: '#C1272D' },
  HAI: { name: 'Haiti',           flag: '🇭🇹', group: 'C', conf: 'CONCACAF', ranking:110, wcWins: 0, wcApps:  1, color: '#00209F' },
  SCO: { name: 'Scotland',        flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', group: 'C', conf: 'UEFA',     ranking: 38, wcWins: 0, wcApps:  8, color: '#003399' },
  USA: { name: 'United States',   flag: '🇺🇸', group: 'D', conf: 'CONCACAF', ranking: 13, wcWins: 0, wcApps: 11, color: '#002868' },
  PAR: { name: 'Paraguay',        flag: '🇵🇾', group: 'D', conf: 'CONMEBOL', ranking: 60, wcWins: 0, wcApps:  8, color: '#D52B1E' },
  AUS: { name: 'Australia',       flag: '🇦🇺', group: 'D', conf: 'AFC',      ranking: 25, wcWins: 0, wcApps:  6, color: '#00843D' },
  TUR: { name: 'Turkey',          flag: '🇹🇷', group: 'D', conf: 'UEFA',     ranking: 28, wcWins: 0, wcApps:  2, color: '#E30A17' },
  GER: { name: 'Germany',         flag: '🇩🇪', group: 'E', conf: 'UEFA',     ranking:  6, wcWins: 4, wcApps: 20, color: '#000000' },
  CUW: { name: 'Curaçao',         flag: '🇨🇼', group: 'E', conf: 'CONCACAF', ranking:115, wcWins: 0, wcApps:  1, color: '#003DA5' },
  CIV: { name: "Côte d'Ivoire",   flag: '🇨🇮', group: 'E', conf: 'CAF',      ranking: 49, wcWins: 0, wcApps:  3, color: '#F77F00' },
  ECU: { name: 'Ecuador',         flag: '🇪🇨', group: 'E', conf: 'CONMEBOL', ranking: 34, wcWins: 0, wcApps:  4, color: '#FFD100' },
  NED: { name: 'Netherlands',     flag: '🇳🇱', group: 'F', conf: 'UEFA',     ranking:  8, wcWins: 0, wcApps: 11, color: '#FF6600' },
  JPN: { name: 'Japan',           flag: '🇯🇵', group: 'F', conf: 'AFC',      ranking: 18, wcWins: 0, wcApps:  8, color: '#BC002D' },
  SWE: { name: 'Sweden',          flag: '🇸🇪', group: 'F', conf: 'UEFA',     ranking: 24, wcWins: 0, wcApps: 12, color: '#006AA7' },
  TUN: { name: 'Tunisia',         flag: '🇹🇳', group: 'F', conf: 'CAF',      ranking: 55, wcWins: 0, wcApps:  6, color: '#E70013' },
  BEL: { name: 'Belgium',         flag: '🇧🇪', group: 'G', conf: 'UEFA',     ranking: 15, wcWins: 0, wcApps: 14, color: '#EF3340' },
  EGY: { name: 'Egypt',           flag: '🇪🇬', group: 'G', conf: 'CAF',      ranking: 70, wcWins: 0, wcApps:  3, color: '#C8102E' },
  IRN: { name: 'Iran',            flag: '🇮🇷', group: 'G', conf: 'AFC',      ranking: 22, wcWins: 0, wcApps:  6, color: '#239F40' },
  NZL: { name: 'New Zealand',     flag: '🇳🇿', group: 'G', conf: 'OFC',      ranking: 97, wcWins: 0, wcApps:  3, color: '#000000' },
  ESP: { name: 'Spain',           flag: '🇪🇸', group: 'H', conf: 'UEFA',     ranking:  7, wcWins: 1, wcApps: 16, color: '#AA151B' },
  CPV: { name: 'Cape Verde',      flag: '🇨🇻', group: 'H', conf: 'CAF',      ranking: 78, wcWins: 0, wcApps:  1, color: '#003893' },
  KSA: { name: 'Saudi Arabia',    flag: '🇸🇦', group: 'H', conf: 'AFC',      ranking: 56, wcWins: 0, wcApps:  6, color: '#006C35' },
  URU: { name: 'Uruguay',         flag: '🇺🇾', group: 'H', conf: 'CONMEBOL', ranking: 18, wcWins: 2, wcApps: 14, color: '#75AADB' },
  FRA: { name: 'France',          flag: '🇫🇷', group: 'I', conf: 'UEFA',     ranking:  2, wcWins: 2, wcApps: 16, color: '#002395' },
  SEN: { name: 'Senegal',         flag: '🇸🇳', group: 'I', conf: 'CAF',      ranking: 20, wcWins: 0, wcApps:  3, color: '#00853F' },
  IRQ: { name: 'Iraq',            flag: '🇮🇶', group: 'I', conf: 'AFC',      ranking: 58, wcWins: 0, wcApps:  1, color: '#CE1126' },
  NOR: { name: 'Norway',          flag: '🇳🇴', group: 'I', conf: 'UEFA',     ranking: 32, wcWins: 0, wcApps:  3, color: '#EF2B2D' },
  ARG: { name: 'Argentina',       flag: '🇦🇷', group: 'J', conf: 'CONMEBOL', ranking:  1, wcWins: 3, wcApps: 18, color: '#74ACDF' },
  ALG: { name: 'Algeria',         flag: '🇩🇿', group: 'J', conf: 'CAF',      ranking: 43, wcWins: 0, wcApps:  4, color: '#006233' },
  AUT: { name: 'Austria',         flag: '🇦🇹', group: 'J', conf: 'UEFA',     ranking: 25, wcWins: 0, wcApps:  7, color: '#ED2939' },
  JOR: { name: 'Jordan',          flag: '🇯🇴', group: 'J', conf: 'AFC',      ranking: 80, wcWins: 0, wcApps:  1, color: '#007A3D' },
  POR: { name: 'Portugal',        flag: '🇵🇹', group: 'K', conf: 'UEFA',     ranking:  6, wcWins: 0, wcApps:  9, color: '#006600' },
  COD: { name: 'DR Congo',        flag: '🇨🇩', group: 'K', conf: 'CAF',      ranking: 72, wcWins: 0, wcApps:  2, color: '#007FFF' },
  UZB: { name: 'Uzbekistan',      flag: '🇺🇿', group: 'K', conf: 'AFC',      ranking:105, wcWins: 0, wcApps:  1, color: '#1EB53A' },
  COL: { name: 'Colombia',        flag: '🇨🇴', group: 'K', conf: 'CONMEBOL', ranking: 19, wcWins: 0, wcApps:  6, color: '#FCD116' },
  ENG: { name: 'England',         flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'L', conf: 'UEFA',     ranking:  5, wcWins: 1, wcApps: 16, color: '#FFFFFF' },
  CRO: { name: 'Croatia',         flag: '🇭🇷', group: 'L', conf: 'UEFA',     ranking: 10, wcWins: 0, wcApps:  7, color: '#FF0000' },
  GHA: { name: 'Ghana',           flag: '🇬🇭', group: 'L', conf: 'CAF',      ranking: 52, wcWins: 0, wcApps:  4, color: '#006B3F' },
  PAN: { name: 'Panama',          flag: '🇵🇦', group: 'L', conf: 'CONCACAF', ranking: 76, wcWins: 0, wcApps:  2, color: '#DA121A' },
}

export const VENUES = {
  AZTECA:     { name: 'Estadio Banorte',          city: 'Mexico City',     country: 'Mexico', capacity: 87000 },
  AKRON:      { name: 'Estadio Akron',            city: 'Guadalajara',     country: 'Mexico', capacity: 49850 },
  BBVA:       { name: 'Estadio BBVA',             city: 'Monterrey',       country: 'Mexico', capacity: 53500 },
  METLIFE:    { name: 'MetLife Stadium',          city: 'East Rutherford', country: 'USA',    capacity: 82500 },
  SOFI:       { name: 'SoFi Stadium',             city: 'Inglewood',       country: 'USA',    capacity: 70000 },
  ATT:        { name: 'AT&T Stadium',             city: 'Arlington',       country: 'USA',    capacity: 80000 },
  LEVIS:      { name: "Levi's Stadium",           city: 'San Jose',        country: 'USA',    capacity: 68500 },
  HARDROCK:   { name: 'Hard Rock Stadium',        city: 'Miami',           country: 'USA',    capacity: 65326 },
  MERCEDESBENZ:{ name: 'Mercedes-Benz Stadium',   city: 'Atlanta',         country: 'USA',    capacity: 71000 },
  LUMEN:      { name: 'Lumen Field',              city: 'Seattle',         country: 'USA',    capacity: 69000 },
  GILLETTE:   { name: 'Gillette Stadium',         city: 'Foxborough',      country: 'USA',    capacity: 65878 },
  NRG:        { name: 'NRG Stadium',              city: 'Houston',         country: 'USA',    capacity: 72220 },
  ARROWHEAD:  { name: 'GEHA Field at Arrowhead Stadium', city: 'Kansas City', country: 'USA', capacity: 76416 },
  LINC:       { name: 'Lincoln Financial Field',  city: 'Philadelphia',    country: 'USA',    capacity: 69328 },
  BMO:        { name: 'BMO Field',                city: 'Toronto',         country: 'Canada', capacity: 45736 },
  BCPLACE:    { name: 'BC Place',                 city: 'Vancouver',       country: 'Canada', capacity: 54500 },
}

export const MATCHES = [
  // GROUP A
  { id:  1, date:'2026-06-11', time:'19:00', home:'MEX', away:'RSA', venue:'AZTECA', group:'A', md:1, round:'gs' },
  { id:  2, date:'2026-06-12', time:'02:00', home:'KOR', away:'CZE', venue:'AKRON', group:'A', md:1, round:'gs' },
  { id:  3, date:'2026-06-25', time:'01:00', home:'CZE', away:'MEX', venue:'AZTECA', group:'A', md:3, round:'gs' },
  { id:  4, date:'2026-06-25', time:'01:00', home:'RSA', away:'KOR', venue:'HARDROCK', group:'A', md:3, round:'gs' },
  { id:  5, date:'2026-06-19', time:'01:00', home:'MEX', away:'KOR', venue:'AZTECA', group:'A', md:2, round:'gs' },
  { id:  6, date:'2026-06-18', time:'16:00', home:'CZE', away:'RSA', venue:'METLIFE', group:'A', md:2, round:'gs' },
  // GROUP B
  { id:  7, date:'2026-06-12', time:'19:00', home:'CAN', away:'BIH', venue:'BMO', group:'B', md:1, round:'gs' },
  { id:  8, date:'2026-06-13', time:'19:00', home:'QAT', away:'SUI', venue:'ARROWHEAD', group:'B', md:1, round:'gs' },
  { id:  9, date:'2026-06-24', time:'19:00', home:'SUI', away:'CAN', venue:'BCPLACE', group:'B', md:3, round:'gs' },
  { id: 10, date:'2026-06-24', time:'19:00', home:'BIH', away:'QAT', venue:'ATT', group:'B', md:3, round:'gs' },
  { id: 11, date:'2026-06-18', time:'22:00', home:'CAN', away:'QAT', venue:'BMO', group:'B', md:2, round:'gs' },
  { id: 12, date:'2026-06-18', time:'19:00', home:'SUI', away:'BIH', venue:'LEVIS', group:'B', md:2, round:'gs' },
  // GROUP C
  { id: 13, date:'2026-06-13', time:'22:00', home:'BRA', away:'MAR', venue:'METLIFE', group:'C', md:1, round:'gs' },
  { id: 14, date:'2026-06-14', time:'01:00', home:'HAI', away:'SCO', venue:'LUMEN', group:'C', md:1, round:'gs' },
  { id: 15, date:'2026-06-24', time:'22:00', home:'SCO', away:'BRA', venue:'HARDROCK', group:'C', md:3, round:'gs' },
  { id: 16, date:'2026-06-24', time:'22:00', home:'MAR', away:'HAI', venue:'LINC', group:'C', md:3, round:'gs' },
  { id: 17, date:'2026-06-20', time:'00:30', home:'BRA', away:'HAI', venue:'NRG', group:'C', md:2, round:'gs' },
  { id: 18, date:'2026-06-19', time:'22:00', home:'SCO', away:'MAR', venue:'SOFI', group:'C', md:2, round:'gs' },
  // GROUP D
  { id: 19, date:'2026-06-13', time:'01:00', home:'USA', away:'PAR', venue:'SOFI', group:'D', md:1, round:'gs' },
  { id: 20, date:'2026-06-14', time:'04:00', home:'AUS', away:'TUR', venue:'MERCEDESBENZ', group:'D', md:1, round:'gs' },
  { id: 21, date:'2026-06-26', time:'02:00', home:'TUR', away:'USA', venue:'ATT', group:'D', md:3, round:'gs' },
  { id: 22, date:'2026-06-26', time:'02:00', home:'PAR', away:'AUS', venue:'ARROWHEAD', group:'D', md:3, round:'gs' },
  { id: 23, date:'2026-06-19', time:'19:00', home:'USA', away:'AUS', venue:'METLIFE', group:'D', md:2, round:'gs' },
  { id: 24, date:'2026-06-20', time:'03:00', home:'TUR', away:'PAR', venue:'GILLETTE', group:'D', md:2, round:'gs' },
  // GROUP E
  { id: 25, date:'2026-06-14', time:'17:00', home:'GER', away:'CUW', venue:'MERCEDESBENZ', group:'E', md:1, round:'gs' },
  { id: 26, date:'2026-06-14', time:'23:00', home:'CIV', away:'ECU', venue:'NRG', group:'E', md:1, round:'gs' },
  { id: 27, date:'2026-06-25', time:'20:00', home:'ECU', away:'GER', venue:'ATT', group:'E', md:3, round:'gs' },
  { id: 28, date:'2026-06-25', time:'20:00', home:'CUW', away:'CIV', venue:'LEVIS', group:'E', md:3, round:'gs' },
  { id: 29, date:'2026-06-20', time:'20:00', home:'GER', away:'CIV', venue:'SOFI', group:'E', md:2, round:'gs' },
  { id: 30, date:'2026-06-21', time:'00:00', home:'ECU', away:'CUW', venue:'LINC', group:'E', md:2, round:'gs' },
  // GROUP F
  { id: 31, date:'2026-06-14', time:'20:00', home:'NED', away:'JPN', venue:'LUMEN', group:'F', md:1, round:'gs' },
  { id: 32, date:'2026-06-15', time:'02:00', home:'SWE', away:'TUN', venue:'BCPLACE', group:'F', md:1, round:'gs' },
  { id: 33, date:'2026-06-25', time:'23:00', home:'TUN', away:'NED', venue:'GILLETTE', group:'F', md:3, round:'gs' },
  { id: 34, date:'2026-06-25', time:'23:00', home:'JPN', away:'SWE', venue:'HARDROCK', group:'F', md:3, round:'gs' },
  { id: 35, date:'2026-06-20', time:'17:00', home:'NED', away:'SWE', venue:'METLIFE', group:'F', md:2, round:'gs' },
  { id: 36, date:'2026-06-21', time:'04:00', home:'TUN', away:'JPN', venue:'MERCEDESBENZ', group:'F', md:2, round:'gs' },
  // GROUP G
  { id: 37, date:'2026-06-15', time:'19:00', home:'BEL', away:'EGY', venue:'LINC', group:'G', md:1, round:'gs' },
  { id: 38, date:'2026-06-16', time:'01:00', home:'IRN', away:'NZL', venue:'BMO', group:'G', md:1, round:'gs' },
  { id: 39, date:'2026-06-27', time:'03:00', home:'NZL', away:'BEL', venue:'NRG', group:'G', md:3, round:'gs' },
  { id: 40, date:'2026-06-27', time:'03:00', home:'EGY', away:'IRN', venue:'LUMEN', group:'G', md:3, round:'gs' },
  { id: 41, date:'2026-06-21', time:'19:00', home:'BEL', away:'IRN', venue:'BCPLACE', group:'G', md:2, round:'gs' },
  { id: 42, date:'2026-06-22', time:'01:00', home:'NZL', away:'EGY', venue:'SOFI', group:'G', md:2, round:'gs' },
  // GROUP H
  { id: 43, date:'2026-06-15', time:'16:00', home:'ESP', away:'CPV', venue:'METLIFE', group:'H', md:1, round:'gs' },
  { id: 44, date:'2026-06-15', time:'22:00', home:'KSA', away:'URU', venue:'ARROWHEAD', group:'H', md:1, round:'gs' },
  { id: 45, date:'2026-06-27', time:'00:00', home:'URU', away:'ESP', venue:'HARDROCK', group:'H', md:3, round:'gs' },
  { id: 46, date:'2026-06-27', time:'00:00', home:'CPV', away:'KSA', venue:'ATT', group:'H', md:3, round:'gs' },
  { id: 47, date:'2026-06-21', time:'16:00', home:'ESP', away:'KSA', venue:'METLIFE', group:'H', md:2, round:'gs' },
  { id: 48, date:'2026-06-21', time:'22:00', home:'URU', away:'CPV', venue:'GILLETTE', group:'H', md:2, round:'gs' },
  // GROUP I
  { id: 49, date:'2026-06-16', time:'19:00', home:'FRA', away:'SEN', venue:'ATT', group:'I', md:1, round:'gs' },
  { id: 50, date:'2026-06-16', time:'22:00', home:'IRQ', away:'NOR', venue:'LEVIS', group:'I', md:1, round:'gs' },
  { id: 51, date:'2026-06-26', time:'19:00', home:'NOR', away:'FRA', venue:'MERCEDESBENZ', group:'I', md:3, round:'gs' },
  { id: 52, date:'2026-06-26', time:'19:00', home:'SEN', away:'IRQ', venue:'LINC', group:'I', md:3, round:'gs' },
  { id: 53, date:'2026-06-22', time:'21:00', home:'FRA', away:'IRQ', venue:'METLIFE', group:'I', md:2, round:'gs' },
  { id: 54, date:'2026-06-23', time:'00:00', home:'NOR', away:'SEN', venue:'BCPLACE', group:'I', md:2, round:'gs' },
  // GROUP J
  { id: 55, date:'2026-06-17', time:'01:00', home:'ARG', away:'ALG', venue:'BBVA', group:'J', md:1, round:'gs' },
  { id: 56, date:'2026-06-17', time:'04:00', home:'AUT', away:'JOR', venue:'NRG', group:'J', md:1, round:'gs' },
  { id: 57, date:'2026-06-28', time:'02:00', home:'JOR', away:'ARG', venue:'BBVA', group:'J', md:3, round:'gs' },
  { id: 58, date:'2026-06-28', time:'02:00', home:'ALG', away:'AUT', venue:'ARROWHEAD', group:'J', md:3, round:'gs' },
  { id: 59, date:'2026-06-22', time:'17:00', home:'ARG', away:'AUT', venue:'AKRON', group:'J', md:2, round:'gs' },
  { id: 60, date:'2026-06-23', time:'03:00', home:'JOR', away:'ALG', venue:'LUMEN', group:'J', md:2, round:'gs' },
  // GROUP K
  { id: 61, date:'2026-06-17', time:'17:00', home:'POR', away:'COD', venue:'SOFI', group:'K', md:1, round:'gs' },
  { id: 62, date:'2026-06-18', time:'02:00', home:'UZB', away:'COL', venue:'BMO', group:'K', md:1, round:'gs' },
  { id: 63, date:'2026-06-27', time:'23:30', home:'COL', away:'POR', venue:'METLIFE', group:'K', md:3, round:'gs' },
  { id: 64, date:'2026-06-27', time:'23:30', home:'COD', away:'UZB', venue:'LEVIS', group:'K', md:3, round:'gs' },
  { id: 65, date:'2026-06-23', time:'17:00', home:'POR', away:'UZB', venue:'HARDROCK', group:'K', md:2, round:'gs' },
  { id: 66, date:'2026-06-24', time:'02:00', home:'COL', away:'COD', venue:'ATT', group:'K', md:2, round:'gs' },
  // GROUP L
  { id: 67, date:'2026-06-17', time:'20:00', home:'ENG', away:'CRO', venue:'GILLETTE', group:'L', md:1, round:'gs' },
  { id: 68, date:'2026-06-17', time:'23:00', home:'GHA', away:'PAN', venue:'LINC', group:'L', md:1, round:'gs' },
  { id: 69, date:'2026-06-27', time:'21:00', home:'PAN', away:'ENG', venue:'ATT', group:'L', md:3, round:'gs' },
  { id: 70, date:'2026-06-27', time:'21:00', home:'CRO', away:'GHA', venue:'NRG', group:'L', md:3, round:'gs' },
  { id: 71, date:'2026-06-23', time:'20:00', home:'ENG', away:'GHA', venue:'MERCEDESBENZ', group:'L', md:2, round:'gs' },
  { id: 72, date:'2026-06-23', time:'23:00', home:'PAN', away:'CRO', venue:'LUMEN', group:'L', md:2, round:'gs' },
  // ROUND OF 32
  { id: 73, date:'2026-06-28', time:'19:00', home:'RSA', away:'CAN', venue:'SOFI',         round:'r32', matchLabel:'R32-1'  },
  { id: 74, date:'2026-06-29', time:'17:00', home:'BRA', away:'JPN', venue:'NRG',          round:'r32', matchLabel:'R32-2'  },
  { id: 75, date:'2026-06-29', time:'20:30', home:'GER', away:'PAR', venue:'GILLETTE',     round:'r32', matchLabel:'R32-3'  },
  { id: 76, date:'2026-06-30', time:'01:00', home:'NED', away:'MAR', venue:'BBVA',         round:'r32', matchLabel:'R32-4'  },
  { id: 77, date:'2026-06-30', time:'17:00', home:'CIV', away:'NOR', venue:'ATT',          round:'r32', matchLabel:'R32-5'  },
  { id: 78, date:'2026-06-30', time:'21:00', home:'FRA', away:'SWE', venue:'METLIFE',      round:'r32', matchLabel:'R32-6'  },
  { id: 79, date:'2026-07-01', time:'01:00', home:'MEX', away:'ECU', venue:'AZTECA',       round:'r32', matchLabel:'R32-7'  },
  { id: 80, date:'2026-07-01', time:'16:00', home:'ENG', away:'COD', venue:'MERCEDESBENZ', round:'r32', matchLabel:'R32-8'  },
  { id: 81, date:'2026-07-01', time:'20:00', home:'BEL', away:'SEN', venue:'LUMEN',        round:'r32', matchLabel:'R32-9'  },
  { id: 82, date:'2026-07-02', time:'00:00', home:'USA', away:'BIH', venue:'LEVIS',        round:'r32', matchLabel:'R32-10' },
  { id: 83, date:'2026-07-02', time:'19:00', home:'ESP', away:'AUT', venue:'SOFI',         round:'r32', matchLabel:'R32-11' },
  { id: 84, date:'2026-07-02', time:'23:00', home:'POR', away:'CRO', venue:'BMO',          round:'r32', matchLabel:'R32-12' },
  { id: 85, date:'2026-07-03', time:'03:00', home:'SUI', away:'ALG', venue:'BCPLACE',      round:'r32', matchLabel:'R32-13' },
  { id: 86, date:'2026-07-03', time:'18:00', home:'AUS', away:'EGY', venue:'ATT',          round:'r32', matchLabel:'R32-14' },
  { id: 87, date:'2026-07-03', time:'22:00', home:'ARG', away:'CPV', venue:'HARDROCK',     round:'r32', matchLabel:'R32-15' },
  { id: 88, date:'2026-07-04', time:'01:30', home:'COL', away:'GHA', venue:'ARROWHEAD',    round:'r32', matchLabel:'R32-16' },
  // ROUND OF 16
  { id: 89, date:'2026-07-04', time:'17:00', home:null, homeLabel:'W R32-1',  away:null, awayLabel:'W R32-2',  venue:'NRG',         round:'r16', matchLabel:'R16-1' },
  { id: 90, date:'2026-07-04', time:'21:00', home:null, homeLabel:'W R32-3',  away:null, awayLabel:'W R32-4',  venue:'LINC',        round:'r16', matchLabel:'R16-2' },
  { id: 91, date:'2026-07-05', time:'20:00', home:null, homeLabel:'W R32-5',  away:null, awayLabel:'W R32-6',  venue:'METLIFE',    round:'r16', matchLabel:'R16-3' },
  { id: 92, date:'2026-07-06', time:'00:00', home:null, homeLabel:'W R32-7',  away:null, awayLabel:'W R32-8',  venue:'AZTECA',     round:'r16', matchLabel:'R16-4' },
  { id: 93, date:'2026-07-06', time:'19:00', home:null, homeLabel:'W R32-9',  away:null, awayLabel:'W R32-10', venue:'ATT',        round:'r16', matchLabel:'R16-5' },
  { id: 94, date:'2026-07-07', time:'00:00', home:null, homeLabel:'W R32-11', away:null, awayLabel:'W R32-12', venue:'LUMEN',      round:'r16', matchLabel:'R16-6' },
  { id: 95, date:'2026-07-07', time:'16:00', home:null, homeLabel:'W R32-13', away:null, awayLabel:'W R32-14', venue:'MERCEDESBENZ', round:'r16', matchLabel:'R16-7' },
  { id: 96, date:'2026-07-07', time:'20:00', home:null, homeLabel:'W R32-15', away:null, awayLabel:'W R32-16', venue:'BCPLACE',    round:'r16', matchLabel:'R16-8' },
  // QUARTER-FINALS
  { id: 97, date:'2026-07-09', time:'20:00', home:null, homeLabel:'W R16-1', away:null, awayLabel:'W R16-2', venue:'GILLETTE', round:'qf', matchLabel:'QF-1' },
  { id: 98, date:'2026-07-10', time:'19:00', home:null, homeLabel:'W R16-3', away:null, awayLabel:'W R16-4', venue:'SOFI',     round:'qf', matchLabel:'QF-2' },
  { id: 99, date:'2026-07-11', time:'21:00', home:null, homeLabel:'W R16-5', away:null, awayLabel:'W R16-6', venue:'HARDROCK', round:'qf', matchLabel:'QF-3' },
  { id:100, date:'2026-07-12', time:'01:00', home:null, homeLabel:'W R16-7', away:null, awayLabel:'W R16-8', venue:'ARROWHEAD', round:'qf', matchLabel:'QF-4' },
  // SEMI-FINALS
  { id:101, date:'2026-07-14', time:'19:00', home:null, homeLabel:'W QF-1', away:null, awayLabel:'W QF-2', venue:'ATT',           round:'sf',    matchLabel:'SF-1'      },
  { id:102, date:'2026-07-15', time:'19:00', home:null, homeLabel:'W QF-3', away:null, awayLabel:'W QF-4', venue:'MERCEDESBENZ', round:'sf',    matchLabel:'SF-2'      },
  // THIRD PLACE
  { id:103, date:'2026-07-18', time:'21:00', home:null, homeLabel:'L SF-1', away:null, awayLabel:'L SF-2', venue:'HARDROCK',     round:'tp',    matchLabel:'3rd Place' },
  // FINAL
  { id:104, date:'2026-07-19', time:'19:00', home:null, homeLabel:'W SF-1', away:null, awayLabel:'W SF-2', venue:'METLIFE',       round:'final', matchLabel:'FINAL'     },
]

export const WC_HISTORY = [
  { nation: 'Brazil',      wins: 5, runner_up: 2, third: 2, apps: 22, bestFinish: 'Champion (2002)' },
  { nation: 'Germany',     wins: 4, runner_up: 4, third: 4, apps: 20, bestFinish: 'Champion (2014)' },
  { nation: 'Italy',       wins: 4, runner_up: 2, third: 1, apps: 18, bestFinish: 'Champion (2006)' },
  { nation: 'Argentina',   wins: 3, runner_up: 3, third: 0, apps: 18, bestFinish: 'Champion (2022)' },
  { nation: 'France',      wins: 2, runner_up: 1, third: 2, apps: 16, bestFinish: 'Champion (2018)' },
  { nation: 'Uruguay',     wins: 2, runner_up: 0, third: 2, apps: 14, bestFinish: 'Champion (1950)' },
  { nation: 'England',     wins: 1, runner_up: 0, third: 0, apps: 16, bestFinish: 'Champion (1966)' },
  { nation: 'Spain',       wins: 1, runner_up: 0, third: 0, apps: 16, bestFinish: 'Champion (2010)' },
  { nation: 'Netherlands', wins: 0, runner_up: 3, third: 1, apps: 11, bestFinish: 'Runner-Up (1978)' },
  { nation: 'Croatia',     wins: 0, runner_up: 0, third: 2, apps:  7, bestFinish: '3rd Place (2022)' },
  { nation: 'Belgium',     wins: 0, runner_up: 0, third: 1, apps: 14, bestFinish: '3rd Place (2018)' },
  { nation: 'Portugal',    wins: 0, runner_up: 0, third: 1, apps:  9, bestFinish: '3rd Place (2022)' },
  { nation: 'Morocco',     wins: 0, runner_up: 0, third: 0, apps:  7, bestFinish: 'Semi-Final (2022)' },
  { nation: 'South Korea', wins: 0, runner_up: 0, third: 0, apps: 11, bestFinish: 'Semi-Final (2002)' },
  { nation: 'USA',         wins: 0, runner_up: 0, third: 0, apps: 11, bestFinish: 'Semi-Final (1930)' },
]
